# This is a basic workflow to help you get started with Actions

name: OpenWRT Build

# Controls when the workflow will run
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: 检查服务器配置
        run: |
          echo "若分配的服务器性能不足，务必及时取消，重新运行！"
          echo -e "------------------------------- CPU信息 -------------------------------\n"
          echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
          echo -e "CPU核心及版本信息: $(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          echo -e "------------------------------- 内存信息 -------------------------------\n"
          echo "已安装内存详细信息: "
          sudo lshw -short -C memory | grep GiB
          
      - name: 最大化磁盘空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          temp-reserve-mb: 100
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          
      - uses: actions/checkout@v4

      - name: 检查磁盘空间
        run: df -h
       
      - name: 安装依赖
        run: |
          sudo apt purge firefox snap*
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y autoconf automake autopoint binutils build-essential bzip2 ccache clang cmake cpio curl flex gawk gettext git gperf intltool libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool llvm msmtp ninja-build p7zip p7zip-full patch pkgconf python3 squashfs-tools swig unzip vim wget xxd zlib1g-dev
          sudo apt autoremove
          sudo apt clean
          df -h
          
      - name: 安装 Go 1.21.1
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
    

      - name: 下载源码、更新 feeds
        run: |
          git clone -b openwrt-24.10 --single-branch --filter=blob:none https://github.com/immortalwrt/immortalwrt
          openwrt/scripts/feeds update -a
          openwrt/scripts/feeds install -a

      # 开启缓存
      - uses: stupidloud/cachewrtbuild@main
        with:
          ccache: 'true'
          toolchain: 'true'
          mixkey: 'x64'
          prefix: 'immortalwrt'

      #下载配置文件
      - name: check build environment and download config file
        run: |
          cd immortalwrt
          make defconfig
          rm .config
          curl -L -o .config "https://raw.githubusercontent.com/hosxy/openwrt-build/refs/heads/master/config-x64"

       #下载构建依赖
      - name: download build dependence
        run: |
          cd openwrt
          make download V=s -j$(nproc)

      #开始编译
      - name: build openwrt
        run: |
          cd openwrt
          make V=s -j$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: openwrt
          path: openwrt/bin/targets/x86/64/*.img.gz
        
          
