# This is a basic workflow to help you get started with Actions

name: OpenWRT Build

# Controls when the workflow will run
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4

      - name: install depences
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler flex gawk gcc-multilib g++-multilib gettext genisoimage git gperf haveged help2man intltool libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool llvm lrzsz msmtp ninja-build p7zip p7zip-full patch pkgconf python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          
      - name: download source and .config file and update feeds
        run: |
          git clone https://github.com/openwrt/openwrt.git -b openwrt-24.10
          curl -L -o openwrt/.config "https://github.com/hosxy/openwrt-build/blob/master/.config"
          openwrt/scripts/feeds update -a
          openwrt/scripts/feeds install -a
          git clone https://github.com/jerrykuku/luci-theme-argon.git openwrt/package/luci-theme-argon
          
      - name: build openwrt
        run: |
          make download V=s -j$(nproc)
          make V=s -j$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: openwrt
          path: openwrt/bin/targets/x86/64/*.img.gz
        
          
